### ISSUE TITLE
Hunting - Automatically end combat when harvesting

### ISSUE THREAD

**Issue by tehqueenbee** [SourcererCodex/Avrae-Workshop#14]
I consistently forget to end combat in between each hunting combat, and when that happens and I get into a new encounter, my PC maintains the old initiative with a new enemy which requires adjustment. it'd be dope if combat automatically ended after using the harvest command. we all use that command after combat is over anyway

**Comment by SourcererCodex** [comment]
ending combat through an alias would basically require another alias, which is essentially is what !end is
Due to the limits of aliasing I won't be addressing this issue
